apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: discover_base_url
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
rules:
- nonResourceURLs:
  - /
  - /openapi/v2
  verbs:
  - get
